import Head from "next/head"
import { getSortedPostsData } from "@/utils/posts"
import Link from "next/link"
import Date from "../components/date"
import utilStyles from "@/styles/utils.module.css"
import Layout from "../components/layout"

const personalDescription =
  "Hi there, I am keguigong, a web develeper living in Shanghai. I write my notes here, from front-end questions to anything that interests me."

export async function getStaticProps() {
  const allPostsData = getSortedPostsData()
  return {
    props: {
      allPostsData
    }
  }
}

export default function Home({ allPostsData }: { [key: string]: any }) {
  return (
    <Layout home>
      <Head>
        <title>Blog.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={utilStyles.headingMd}>
        <p>{personalDescription}</p>
      </section>
      <section>
        <h2 className={utilStyles.headingLg}>Blog.</h2>
        <ul>
          {allPostsData.map(({ id, date, title }: { [key: string]: any }) => (
            <li className={utilStyles.listItem} key={id}>
              <Link href={`/posts/${id}`}>{title}</Link>
              <br />
              <small className={utilStyles.lightText}>
                <Date dateString={date} />
              </small>
            </li>
          ))}
        </ul>
      </section>
      <p>
        <br />
        <a href="https://github.com/keguigong">GitHub</a> •{" "}
        <a href="https://www.behance.net/keguigong">Behance</a> •{" "}
        <a href="https://www.instagram.com/keguigong/">Instagram</a>
      </p>
    </Layout>
  )
}
